### ISSUE TITLE
Last update (20190616) broke encrypted device

### ISSUE THREAD

**Issue by julien-tdx** [omnirom/android_device_xiaomi_beryllium#1]
TLDR: DO NOT UPDATE your poco f1 20190616, build is broken. If you did and came here, only solution is reboot to TWRP, backup your data, reflash 20190609, restore, and skipe this update.

----

After updating as usual the encrypted phone rebooted straight to the "data corrupted screen" without asking for any schema or passphrase to decrypt partition.
TWRP can decrypt the data fine though...

Currently doing an emergency backup, will try to reflash the older rom.

**Comment by julien-tdx** [comment]
After some investigation, you cannot simply rollback an earlier version, even with system partition wipe. The problem is still there. TWRP can decrypt the partition fine though.

Quite a few encryption-related commits in this build, it's very likely one of them is responsible: https://gerrit.omnirom.org/#/q/status:merged

I spoke with another user on Telegram which had the same problem on the potter build, this may affect all devices...

**Comment by avrelaun** [comment]
After wiping data AND internal storage from twrp, twrp still asks for schema to unlock after reboot. It still can unlock it though.

**Comment by julien-tdx** [comment]
I reflashed 20190609, restore my data, reupdated the phone, and reproduced the problem.

I noticed something though: on the first reboot after updating, it asks for the schema as usual, but then it shows the decrypting fail screen with the reset button. After rebooting it goes straight to this decrypting fail screen.

**Comment by julien-tdx** [comment]
I flashed a fresh 20190616 build, after wiping everything and formatting data first, and the phone bootloops: the omni boot animation get stuck and it reboots again and again.

Reverting to 20190609 for now...

**Comment by julien-tdx** [comment]
it was an omnirom problem, fixed by the team and they released a new build before the next scheduled one to fix it.
